# _config.yml
title: "Sintaxis de C++"
description: "Apuntes sobre la sintaxis de C++"
# Indica que el tema remoto será Tactile en la versión 0.2.0
remote_theme: pages-themes/tactile@v0.2.0

# Habilita el plugin jekyll-remote-theme para que Jekyll descargue Tactile
plugins:
  - jekyll-remote-theme

# Baseurl para que las rutas empiecen en /cppsyntax
baseurl: "/cppsyntax"

# Define la colección “unidades” como antes
collections:
  unidades:
    output: true
    permalink: /unidades/:name/

# Resaltador de sintaxis (Tactile usa rouge por defecto, pero lo declaramos también)
highlighter: rouge

