# _config.yml
title: "Sintaxis de C++"
theme: tactile

# Como tu sitio vive en https://JorxGomariz.github.io/cppsyntax,
# tienes que indicar baseurl: "/cppsyntax"
baseurl: "/cppsyntax"  

# Colección de “unidades” que generará rutas en /cppsyntax/unidades/...
collections:
  unidades:
    output: true
    permalink: /unidades/:name/

# Para que Rouge resalte sintaxis
highlighter: rouge
