title: "Sintaxis de C++"
description: "Apuntes sobre la sintaxis de C++"
theme: minima  

baseurl: "/cppsyntax"

collections:
  unidades:
    output: true
    permalink: /unidades/:name/

highlighter: rouge


